USE [master]
GO
/****** Object:  Database [EF_App]    Script Date: 10/21/2021 1:16:03 AM ******/
CREATE DATABASE [EF_App]

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EF_App].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [EF_App] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [EF_App] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [EF_App] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [EF_App] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [EF_App] SET ARITHABORT OFF 
GO
ALTER DATABASE [EF_App] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [EF_App] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [EF_App] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [EF_App] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [EF_App] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [EF_App] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [EF_App] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [EF_App] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [EF_App] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [EF_App] SET  DISABLE_BROKER 
GO
ALTER DATABASE [EF_App] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [EF_App] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [EF_App] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [EF_App] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [EF_App] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [EF_App] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [EF_App] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [EF_App] SET RECOVERY FULL 
GO
ALTER DATABASE [EF_App] SET  MULTI_USER 
GO
ALTER DATABASE [EF_App] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [EF_App] SET DB_CHAINING OFF 
GO
ALTER DATABASE [EF_App] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [EF_App] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [EF_App] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [EF_App] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'EF_App', N'ON'
GO
ALTER DATABASE [EF_App] SET QUERY_STORE = OFF
GO
USE [EF_App]
GO
/****** Object:  Table [dbo].[Productos]    Script Date: 10/21/2021 1:16:03 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Productos](
	[IdProducto] [int] IDENTITY(1,1) NOT NULL,
	[IdUsuario] [int] NOT NULL,
	[Nombre] [nvarchar](50) NOT NULL,
	[Descripcion] [nvarchar](100) NOT NULL,
	[Precio] [decimal](18, 2) NOT NULL,
 CONSTRAINT [PK_Productos] PRIMARY KEY CLUSTERED 
(
	[IdProducto] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Usuarios]    Script Date: 10/21/2021 1:16:03 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuarios](
	[IdUsuario] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [nvarchar](50) NOT NULL,
	[Apellido] [nvarchar](50) NOT NULL,
	[Email] [nvarchar](50) NOT NULL,
	[Password] [nvarchar](50) NOT NULL,
	[Edad] [int] NOT NULL,
 CONSTRAINT [PK_Usuarios] PRIMARY KEY CLUSTERED 
(
	[IdUsuario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Ventas]    Script Date: 10/21/2021 1:16:03 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Ventas](
	[IdVenta] [int] IDENTITY(1,1) NOT NULL,
	[IdUsuario] [int] NOT NULL,
	[Monto] [decimal](18, 2) NOT NULL,
 CONSTRAINT [PK_Ventas] PRIMARY KEY CLUSTERED 
(
	[IdVenta] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[VentasProductos]    Script Date: 10/21/2021 1:16:03 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VentasProductos](
	[IdVenta] [int] NOT NULL,
	[IdProducto] [int] NOT NULL,
 CONSTRAINT [PK_VentasProductos] PRIMARY KEY CLUSTERED 
(
	[IdVenta] ASC,
	[IdProducto] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Productos]  WITH CHECK ADD  CONSTRAINT [FK_Productos_Usuarios] FOREIGN KEY([IdUsuario])
REFERENCES [dbo].[Usuarios] ([IdUsuario])
GO
ALTER TABLE [dbo].[Productos] CHECK CONSTRAINT [FK_Productos_Usuarios]
GO
ALTER TABLE [dbo].[Ventas]  WITH CHECK ADD  CONSTRAINT [FK_Ventas_Usuarios] FOREIGN KEY([IdUsuario])
REFERENCES [dbo].[Usuarios] ([IdUsuario])
GO
ALTER TABLE [dbo].[Ventas] CHECK CONSTRAINT [FK_Ventas_Usuarios]
GO
ALTER TABLE [dbo].[VentasProductos]  WITH CHECK ADD  CONSTRAINT [FK_VentasProductos_Productos] FOREIGN KEY([IdProducto])
REFERENCES [dbo].[Productos] ([IdProducto])
GO
ALTER TABLE [dbo].[VentasProductos] CHECK CONSTRAINT [FK_VentasProductos_Productos]
GO
ALTER TABLE [dbo].[VentasProductos]  WITH CHECK ADD  CONSTRAINT [FK_VentasProductos_Ventas] FOREIGN KEY([IdVenta])
REFERENCES [dbo].[Ventas] ([IdVenta])
GO
ALTER TABLE [dbo].[VentasProductos] CHECK CONSTRAINT [FK_VentasProductos_Ventas]
GO
USE [master]
GO
ALTER DATABASE [EF_App] SET  READ_WRITE 
GO
